Initial commit for UBI images for RH certification
Rookout/rookout-k8s-operator pull request #19
Opened 2022-03-18 21:31 UTC by jhendrick

Updates -
**new file:   Dockerfile.ubi** - Updated with UBI image required for RH cert
**new file:   InitContainer.Dockerfile.ubi** - Updated with UBI image required for RH cert

**modified:   PROJECT** - config-3alpha no longer supported
_WARN[0000] Config version 3-alpha has been stabilized as 3, and 3-alpha is no longer supported. Run `operator-sdk alpha config-3alpha-to-3` to upgrade your PROJECT config file to version 3 
Error: error reading configuration: unable to load the configuration: unable to create config for version "3-alpha": version 3-alpha is not supported_

Ran: 'operator-sdk alpha config-3alpha-to-3' to update
_Your PROJECT config file has been converted from version 3-alpha to 3. Please make sure all config data is correct._

**new file:   config/manifests/kustomization.yaml** - running 'make bundle' initially gives:
_/Users/jhendrick/rookout/workspace/operator/rookout-k8s-operator/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/jhendrick/rookout/workspace/operator/rookout-k8s-operator/config/manifests'
FATA[0000] Error generating bundle manifests: could not find manager deployment, should have label control-plane=controller-manager_ 

This file is required to be able to successfully run the bundle command

2022-03-18 21:31 UTC, jhendrick commented
/jira open task

2022-03-18 21:33 UTC, jhendrick commented
Also note the updates to the PROJECT file now contain:
    _# TODO(user): Uncomment the below line if this resource's CRD is namespace scoped, else delete it.
    # namespaced: true
  # TODO(user): Uncomment the below line if this resource implements a controller, else delete it.
  # controller: true_

and 

_# TODO(user): Update the package path for your API if the below value is incorrect._

Can we validate if these are required?

2022-03-19 18:40 UTC, ElDuderinos requested changes

2022-03-19 18:40 UTC, ElDuderinos commented on Dockerfile.ubi
> +# Refer to https://github.com/GoogleContainerTools/distroless for more details
I think this comment is relevant anymore, right?

2022-03-19 18:40 UTC, ElDuderinos commented on Dockerfile.ubi
> +COPY ./rook.jar /var/rookout/rook.jar
It's a good opportunity to update the rook.jar with the most recent one from maven. (commit the new jar file)

2022-03-21 18:42 UTC, jhendrick commented on Dockerfile.ubi
> +COPY ./rook.jar /var/rookout/rook.jar
Updated new jar

2022-03-22 20:17 UTC, ElDuderinos approved these changes

2022-03-22 21:00 UTC, acornett21 commented on Dockerfile.ubi
> +COPY ./rook.jar /var/rookout/rook.jar
@jhendrick These docker files will need `labels` and `licenses` to pass certification. See example documentation [here](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/program-on-boarding/technical-prerequisites#example-dockerfile-for-container-application).

2022-03-22 21:05 UTC, merged

2022-03-22 21:11 UTC, acornett21 commented
> Can we validate if these are required?



> Also note the updates to the PROJECT file now contain:
> 
> ```
>     # TODO(user): Uncomment the below line if this resource's CRD is namespace scoped, else delete it.
>     # namespaced: true
>   # TODO(user): Uncomment the below line if this resource implements a controller, else delete it.
>   # controller: true
> ```
> 
> and
> 
> `# TODO(user): Update the package path for your API if the below value is incorrect.`
> 
> Can we validate if these are required?

You probably want `namespaced: true` and `namespaced: true`

2022-03-22 21:18 UTC, jhendrick commented
> 

Thanks @acornett21 I assume you meant namespaced: true and controller: true?

2022-03-22 21:30 UTC, jhendrick commented on Dockerfile.ubi
> +COPY ./rook.jar /var/rookout/rook.jar
Thanks for chiming in here @acornett21, appreciate it. We'll make sure to add those.

2022-03-22 21:31 UTC, acornett21 commented
@jhendrick Yea both true! copy paste fails me again!